"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vendor",
  description: "Generated by create next app",
};

export default function OrdersLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = new QueryClient();
  return (
    <QueryClientProvider client={client}>
      <main>{children}</main>
    </QueryClientProvider>
  );
}
